### ISSUE TITLE
Would that be a bug?

### ISSUE THREAD

**Issue by sebastianjnuwu** [bajrangCoder/MarkdownCompiler#2]
Items placed in this way, the "•" is separated and centralized while the one that accompanies it is not:

- Normal 
- Normal
- Normal 

Plugin:
```
•     normalizing 
•       Normal
•         test
```

How it should be:
Plugin:
```
   • normalizing 
     • Normal
        • test
```

**Comment by bajrangCoder** [comment]
it might be bug let check and fix it
if you have patch, feel free to pr it

**Comment by bajrangCoder** [comment]
I thought it's due to Acode new update .
Because previously it worked fine

**Comment by sebastianjnuwu** [comment]
> I thought it's due to Acode new update . Because previously it worked fine

That must be it....

**Comment by sebastianjnuwu** [comment]
Would that also be a bug? The images in the TAG table don't seem to take up everything!

![Screenshot_20230713-154528](https://github.com/bajrangCoder/acode-plugin-markdown-styler/assets/101356556/3c0758ae-f697-445f-ab68-ca794aa4fac0)

**Comment by bajrangCoder** [comment]
Yes

**Comment by bajrangCoder** [comment]
It's seems, this bug is no more
