### ISSUE TITLE
Links to headings within the document open external browser

### ISSUE THREAD

**Issue by mzalal** [bajrangCoder/MarkdownCompiler#3]
**Description:**
Clicking on a link that references a heading within the document opens an external browser instead of scrolling to the heading.

**Example:**
```markdown
<!-- This link should scroll down to the heading, not open the browser -->
[Link](#foo-heading)

.
.
.

## Foo Heading
```

**Comment by bajrangCoder** [comment]
Oo sorry it's a bug.
Soon it will be fixed.
Thanks for reporting 🤗

**Comment by bajrangCoder** [comment]
Working on this issue, soon there will be a update

**Comment by bajrangCoder** [comment]
Check update `v1.0.4`
