### ISSUE TITLE
A bug that blocks tha app menu options

### ISSUE THREAD

**Issue by houxitsystems** [bajrangCoder/MarkdownCompiler#4]
This plugin disables the app;s menu and setting options buttons after being installed on acode

**Comment by bajrangCoder** [comment]
Share recording and your Acode version, etc..

**Comment by vulovix** [comment]
It's really easy to reproduce this bug, it freezes whole application and you can only switch between sidebar files. The only solution to unstuck from this is to go to app info and clear whole data, and then add folders again without installing MarkdownCompiler.

Steps to reproduce: 

1. Open SomeFile.md
2. Install MarkdownCompiler
3. Open Settings => you won't be able to click anything, nothing reacts on click
4. Try to uninstall the plugin => opens empty gray screen and you need to close the app (back doesn't work)

One more bug that i found is that it wont load relative image withing the active directory. File structure example

Data/Images/some-image.png

Notes/Folder/MyNote.md 

`[MyImage](../../Data/Images/some-image.png)` => will show broken image with "alt" attribute

**Comment by bajrangCoder** [comment]
I'm not able to reproduce, it's working fine .
I have tried your step for reproducing but I can't reproduce.

Share recording which will help in fixing the issues.

> One more bug that i found is that it wont load relative image withing the active directory. File structure example

I will fix this

**Comment by bajrangCoder** [comment]
Check update `v1.0.4`
